## Cartesian controller
cartesian_controller:
  update_rate: 50.0

  # twist controller parameters
  chain_base_link: arm_podest_link
  chain_tip_link: arm_6_link
  base_compensation: false
  base_active: false
  max_vel_lin: 0.5
  max_vel_rot: 0.5

  # damping parameters
  damping_method: 0  #MANIPULABILITY
  damping_factor: 0.2
  lambda0: 0.1
  wt: 0.005

  JLA_active: true 
  enforce_limits: true
  tolerance: 5.0 
  
  # frame_tracker + interactive_marker
  tracking_frame: arm_target
  root_frame: world
  movable_trans: true
  movable_rot: true
  pid_trans: {p: 4.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  pid_rot: {p: 4.0, i: 0.0, d: 0.0, i_clamp: 0.0}
