## Cartesian controller
cartesian_controller:
  update_rate: 50.0

  # twist controller parameters
  base_link: arm_0_link
  tip_link: arm_6_link
  base_compensation: false
  base_active: false
  base_ratio: 0.4
  max_vel_lin: 0.5
  max_vel_rot: 0.5

  # frame_tracker + interactive_marker
  active_frame: arm_6_link
  tracking_frame: arm_target
  root_frame: world
  movable_trans: true
  movable_rot: true
  pid_trans_x: {p: 1 , i: 0.056, d: 0.0, i_clamp: 0.0}
  pid_trans_y: {p: 1 , i: 0.056, d: 0.0, i_clamp: 0.0}
  pid_trans_z: {p: 1 , i: 0.056, d: 0.0, i_clamp: 0.0}
  pid_rot: {p: 1 , i: 0.0, d: 0.0, i_clamp: 0.0}
