#joint trajectory controller and Cartesian controller
arm_controller:
  #all
  joint_names: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]

  ## trajectory controller parameters
  #ptp_vel: 1.5 # rad/sec
  #ptp_acc: 0.2 # rad/sec^2
  #max_error: 0.25 # rad
  #overlap_time: 0.4
  #frequency: 68
  #operation_mode: velocity

  # twist controller parameters
  base_link: arm_base_link
  tip_link: arm_7_link

  # frame_tracker + interactive_marker
  active_frame: arm_7_link
  tracking_frame: arm_7_target
  root_frame: world
  movable_trans: true
  movable_rot: true
  pid_trans: {p: 2.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  pid_rot: {p: 2.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  update_rate: 68.0
  max_vel_lin: 10.0
  max_vel_rot: 6.28
  
  
  
  
  
  
  


arm_1_joint_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: arm_1_joint  
arm_2_joint_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: arm_2_joint
arm_3_joint_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: arm_3_joint  
arm_4_joint_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: arm_4_joint  
arm_5_joint_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: arm_5_joint
arm_6_joint_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: arm_6_joint  
arm_7_joint_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: arm_7_joint
  
  
#FXM
#the arm_2_joint just cannot be velocity controlled somehow
#thus, let it be effort controlled by the gazebo_ros_control plugin internally
#by setting the following PID the control mode switches from VELOCITY (=SetVelocity) to VELOCITY_PID (=SetForce)!
gazebo_ros_control/pid_gains:
  #arm_2_joint: {p: 300.0, i: 0.0, d: 0.0}
  arm_2_joint: {p: 180.0, i: 360000, d: 0.0225}
  #Ziegler-Nichols: K_u=300 T_u=0.001
  
