#joint trajectory controller and Cartesian controller
arm_controller:
  #all
  joint_names: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]

  #controller adapter
  update_rate: 100.0
  max_vel_command_silence: 0.5
  
  # trajectory controller parameters
  ptp_vel: 1.2566 # rad/sec
  ptp_acc: 5.2360 # rad/sec^2
  max_error: 0.25 # rad
  overlap_time: 0.4
  frequency: 100
  operation_mode: velocity

  # twist controller parameters
  base_link: arm_base_link
  tip_link: arm_7_link



#position controller
#arm_position_pid_gains: &arm_position_pid_gains
  #p: 2000.0
  #d: 0.0
  #i: 1.0
  #i_clamp: 1.0

arm_1_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm_1_joint  
  pid: {p: 240, i: 4800.0, d: 3.0, i_clamp: 81.5}  
  #Ziegler-Nichols: K_u = 400, T_u = 0.1
arm_2_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm_2_joint
  pid: {p: 780.0, i: 5200.0, d: 350, i_clamp: 48.0}  
  #Ziegler-Nichols: K_u = 1300, T_u = 0.30
arm_3_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm_3_joint
  pid: {p: 240.0, i: 7384.0, d: 1.95, i_clamp: 48.0}
  #Ziegler-Nichols: K_u = 400, T_u = 0.065
arm_4_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm_4_joint  
  pid: {p: 1800.0, i: 4628.6, d: 20, i_clamp: 48.0}
  #Ziegler-Nichols K_u=540, T_u=0.14 / But values tweaked
arm_5_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm_5_joint
  pid: {p: 30.0, i: 0, d: 3.0, i_clamp: 48.0}
  #Ziegler-Nichols K_u = 30, T_u=0.1625 / But tweaked values because of bad performance
arm_6_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm_6_joint
  pid: {p: 300.0, i: 18462.0, d: 30, i_clamp: 15.0}
  #Ziegler-Nichols K_u=500 T_u=0.0325 / d Value tweaked
arm_7_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm_7_joint
  pid: {p: 180.0, i: 10000.0, d: 8, i_clamp: 15.0}
  #Ziegler-Nichols K_u = 300, T_u = 0.036 / D value tweaked



#velocity controller
#arm_velocity_pid_gains: &arm_velocity_pid_gains
  #p: 2000.0
  #d: 0.0
  #i: 1.0
  #i_clamp: 1.0

arm_1_joint_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: arm_1_joint  
  pid: {p: 80.0, i: 0.0, d: 0.0, i_clamp: 0.0}
arm_2_joint_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: arm_2_joint
  pid: {p: 50.0, i: 180.0, d: 0.2, i_clamp: 48.0}
  #pid: {p: 20.0, i: 200.0, d: 0.02, i_clamp: 48.0}
  #pid: {p: 240.0, i: 640.0, d: 22.5, i_clamp: 48.0}
arm_3_joint_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: arm_3_joint  
  pid: {p: 50.0, i: 0.0, d: 0.0, i_clamp: 48.0}
arm_4_joint_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: arm_4_joint  
  pid: {p: 324.0, i: 3240.0, d: 0.081, i_clamp: 48.0}
  #Ziegler-Nichols: K_u = 540, T_u = 0.002
arm_5_joint_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: arm_5_joint
  pid: {p: 20, i: 0.0, d: 0.0, i_clamp: 48.0}
  #Ziegler-Nichols: K_u = 40,  T_u = 0.002 / But just tweaked P performance is good
arm_6_joint_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: arm_6_joint  
  pid: {p: 16.2, i: 161.9, d: 0.0, i_clamp: 15.0}
  #Ziegler-Nichols K_u = 27, T_u = 0.002 / But values tweaked because of bad performance
arm_7_joint_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: arm_7_joint
  pid: {p: 12.0, i: 120.0, d: 0.0, i_clamp: 15.0}  
  #Ziegler-Nichols K_u = 20, T_u =0.002 / But values tweaked because of bad performance
  
