#joint trajectory controller and Cartesian controller
arm_controller:
  #all
  joint_names: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]

  #controller adapter
  update_rate: 100.0
  max_vel_command_silence: 0.5
  
  # trajectory controller parameters
  ptp_vel: 1.2566 # rad/sec
  ptp_acc: 5.2360 # rad/sec^2
  max_error: 0.25 # rad
  overlap_time: 0.4
  frequency: 100
  operation_mode: velocity

  # twist controller parameters
  base_link: arm_base_link
  tip_link: arm_7_link



#position controller
#arm_position_pid_gains: &arm_position_pid_gains
  #p: 2000.0
  #d: 0.0
  #i: 1.0
  #i_clamp: 1.0

arm_1_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm_1_joint
  #pid: {p: 400.0, i: 0.0, d: 30.0, i_clamp: 1.0}
  pid: {p: 400.0, i: 0.0, d: 0.0, i_clamp: 0.0}
arm_2_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm_2_joint
  #pid: {p: 900.0, i: 0.0, d: 30.0, i_clamp: 1.0}
  pid: {p: 900.0, i: 0.0, d: 0.0, i_clamp: 0.0}
arm_3_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm_3_joint
  #pid: {p: 330.0, i: 0.0, d: 10.0, i_clamp: 1.0}
  pid: {p: 330.0, i: 0.0, d: 0.0, i_clamp: 0.0}
arm_4_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm_4_joint
  #pid: {p: 200.0, i: 0.0, d: 10.0, i_clamp: 1.0}
  pid: {p: 200.0, i: 0.0, d: 0.0, i_clamp: 0.0}
arm_5_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm_5_joint
  #pid: {p: 80.0, i: 0.0, d: 0.0, i_clamp: 1.0}
  pid: {p: 80.0, i: 0.0, d: 0.0, i_clamp: 0.0}
arm_6_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm_6_joint
  #pid: {p: 80.0, i: 0.0, d: 0.0, i_clamp: 1.0}
  pid: {p: 80.0, i: 0.0, d: 0.0, i_clamp: 0.0}
arm_7_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm_7_joint
  #pid: {p: 80.0, i: 0.0, d: 0.0, i_clamp: 1.0}
  pid: {p: 80.0, i: 0.0, d: 0.0, i_clamp: 0.0}





#velocity controller
#arm_velocity_pid_gains: &arm_velocity_pid_gains
  #p: 2000.0
  #d: 0.0
  #i: 1.0
  #i_clamp: 1.0

arm_1_joint_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: arm_1_joint
  pid: {p: 1.0, i: 0.0, d: 0.0, i_clamp: 0.0}
arm_2_joint_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: arm_2_joint
  pid: {p: 300.0, i: 20.0, d: 0.0, i_clamp: 80.0}
arm_3_joint_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: arm_3_joint
  pid: {p: 5.0, i: 0.0, d: 0.0, i_clamp: 0.0}
arm_4_joint_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: arm_4_joint
  pid: {p: 60.0, i: 5.0, d: 0.0, i_clamp: 20.0}
arm_5_joint_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: arm_5_joint
  pid: {p: 5.0, i: 0.0, d: 0.0, i_clamp: 0.0}
arm_6_joint_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: arm_6_joint
  pid: {p: 5.0, i: 0.0, d: 0.0, i_clamp: 0.0}
arm_7_joint_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: arm_7_joint
  pid: {p: 1.0, i: 0.0, d: 0.0, i_clamp: 0.0}
