#Cartesian controller
arm_controller:
  joint_names: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]

  # twist controller parameters
  base_link: arm_base_link
  tip_link: arm_7_link
  #base_active: false
  #base_ratio: 0.0
  
  max_vel_command_silence: 0.5

  # frame_tracker + interactive_marker
  active_frame: arm_7_link
  tracking_frame: arm_7_target
  root_frame: world
  movable_trans: true
  movable_rot: true
  pid_trans_x: {p: 6.0, i: 8.0, d: 1.125, i_clamp: 0.0}
  pid_trans_y: {p: 6.0, i: 8.0, d: 1.125, i_clamp: 0.0}
  pid_trans_z: {p: 6.0, i: 8.0, d: 1.125, i_clamp: 0.0}
  pid_rot: {p: 6.0, i: 8.0, d: 1.125, i_clamp: 0.0}
  update_rate: 68.0
  max_vel_lin: 10.0
  max_vel_rot: 6.28



# joint trajectory controller for position HW-Interface
arm_follow_joint_trajectory_controller_pos:
  type: position_controllers/JointTrajectoryController
  topic: "test"
  joints:
     - arm_1_joint
     - arm_2_joint
     - arm_3_joint
     - arm_4_joint
     - arm_5_joint
     - arm_6_joint
     - arm_7_joint
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.5
      arm_1_joint: {trajectory: 0.1, goal: 0.1}
      arm_2_joint: {trajectory: 0.1, goal: 0.1}
      arm_3_joint: {trajectory: 0.1, goal: 0.1}
      arm_4_joint: {trajectory: 0.1, goal: 0.1}
      arm_5_joint: {trajectory: 0.1, goal: 0.1}
      arm_6_joint: {trajectory: 0.1, goal: 0.1}
      arm_7_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

# joint trajectory controller for velocity HW-Interface
arm_follow_joint_trajectory_controller_vel:
  type: velocity_controllers/JointTrajectoryController
  topic: "test"
  joints:
     - arm_1_joint
     - arm_2_joint
     - arm_3_joint
     - arm_4_joint
     - arm_5_joint
     - arm_6_joint
     - arm_7_joint
  gains:
    arm_1_joint: {p: 10, i: 0.0, d: 0.0, i_clamp: 0.0}
    arm_2_joint: {p: 10, i: 0.0, d: 0.0, i_clamp: 0.0}
    arm_3_joint: {p: 10, i: 0.0, d: 0.0, i_clamp: 0.0}
    arm_4_joint: {p: 10, i: 0.0, d: 0.0, i_clamp: 0.0}
    arm_5_joint: {p: 10, i: 0.0, d: 0.0, i_clamp: 0.0}
    arm_6_joint: {p: 10, i: 0.0, d: 0.0, i_clamp: 0.0}
    arm_7_joint: {p: 10, i: 0.0, d: 0.0, i_clamp: 0.0}
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.5
      arm_1_joint: {trajectory: 0.1, goal: 0.1}
      arm_2_joint: {trajectory: 0.1, goal: 0.1}
      arm_3_joint: {trajectory: 0.1, goal: 0.1}
      arm_4_joint: {trajectory: 0.1, goal: 0.1}
      arm_5_joint: {trajectory: 0.1, goal: 0.1}
      arm_6_joint: {trajectory: 0.1, goal: 0.1}
      arm_7_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10



##position controller
arm_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
     - arm_1_joint
     - arm_2_joint
     - arm_3_joint
     - arm_4_joint
     - arm_5_joint
     - arm_6_joint
     - arm_7_joint
     
arm_1_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: arm_1_joint
arm_2_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: arm_2_joint
arm_3_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: arm_3_joint
arm_4_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: arm_4_joint
arm_5_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: arm_5_joint
arm_6_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: arm_6_joint
arm_7_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: arm_7_joint


#velocity controller
arm_velocity_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
     - arm_1_joint
     - arm_2_joint
     - arm_3_joint
     - arm_4_joint
     - arm_5_joint
     - arm_6_joint
     - arm_7_joint

arm_1_joint_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: arm_1_joint
arm_2_joint_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: arm_2_joint
arm_3_joint_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: arm_3_joint
arm_4_joint_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: arm_4_joint
arm_5_joint_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: arm_5_joint
arm_6_joint_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: arm_6_joint
arm_7_joint_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: arm_7_joint
