device: /dev/pcan32
baudrate: 500K
sync_interval: 10
chains: ["arm_controller"]
arm_controller:
  joint_names: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
  motor_direction: [1,1,1,1,1,1,1]
  module_ids: [3,4,5,6,7,8,9]


####  OLD FORMAT
#devices:
  #- name: /dev/pcan32
    #baudrate: 500K
    #sync_interval: 10
## - name: /dev/pcan33
##   baudrate: 1M
##   sync_interval: 5
#chains: ["arm_controller"]
