joint_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  topic: "test"
  joints:
    - arm_1_joint
    - arm_2_joint
    - arm_3_joint
    - arm_4_joint
    - arm_5_joint
    - arm_6_joint
    - arm_7_joint
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.5
    arm_1_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
  required_drive_mode: 7

joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
    
