joint_limits:
  arm_1_joint:
    has_velocity_limits: true
    max_velocity: 0.30
    has_acceleration_limits: true
    max_acceleration: 1.6755
  arm_5_joint:
    has_velocity_limits: true
    max_velocity: 1.1066
    has_acceleration_limits: true
    max_acceleration: 5.2360
  arm_3_joint:
    has_velocity_limits: true
    max_velocity: 1.1066
    has_acceleration_limits: true
    max_acceleration: 5.2360
  arm_2_joint:
    has_velocity_limits: true
    max_velocity: 1.1066
    has_acceleration_limits: true
    max_acceleration: 5.2360
  arm_6_joint:
    has_velocity_limits: true
    max_velocity: 1.1066
    has_acceleration_limits: true
    max_acceleration: 5.2360
  arm_7_joint:
    has_velocity_limits: true
    max_velocity: 1.1066
    has_acceleration_limits: true
    max_acceleration: 5.2360
  arm_4_joint:
    has_velocity_limits: true
    max_velocity: 1.1066
    has_acceleration_limits: true
    max_acceleration: 5.2360
